# utils/message_codes.py

"""
This file defines the message codes for multilanguage in the frontend
Using i18n standard, please check multilanguage folder to add or modify messages
assets/i18n/<lang>
"""

# Common Messages
OK_MSG = "OK_MSG"
CREATED_MSG = "CREATED_MSG"
NOT_FOUND_MSG = "NOT_FOUND_MSG"
CONFLICT_MSG = "CONFLICT_MSG"
UNPROCESSABLE_ENTITY_MSG = "UNPROCESSABLE_ENTITY_MSG"
INTERNAL_SERVER_ERROR_MSG = "INTERNAL_SERVER_ERROR_MSG"
SERVER_TIMEOUT_MSG = "SERVER_TIMEOUT_MSG"
NO_DATA = "NO_DATA"
ERROR_MSG = "ERROR_MSG"
SUCCESS_MSG = "SUCCESS_MSG"
INCORRECT_REQUEST_PARAM = 'INCORRECT_REQUEST_PARAM'
UNAUTHORIZED = "UNAUTHORIZED"
PERMISSION_ERROR = "PERMISSION_ERROR"

# Common Validations Messages
INVALID_ID = "INVALID_ID"  # Invalid Id

# Car Validations Messages
CAR_NOT_FOUND = "CAR_NOT_FOUND"  # CAR not found
CAR_SUCCESSFULLY_UPDATED = "CAR_SUCCESSFULLY_UPDATED"
CAR_SUCCESSFULLY_DELETED = "CAR_SUCCESSFULLY_DELETED"
CAR_SUCCESSFULLY_CREATED = "CAR_SUCCESSFULLY_CREATED"
CAR_ALREADY_EXIST = "CAR_ALREADY_EXIST"
CAR_PHOTO_REQUIRED = "CAR_PHOTO_REQUIRED"
CAR_MODEL_REQUIRED = "CAR_MODEL_REQUIRED"
CAR_TYPE_REQUIRED = "CAR_TYPE_REQUIRED"
CAR_PLATE_REQUIRED = "CAR_PLATE_REQUIRED"
CAR_BRAND_REQUIRED = "CAR_BRAND_REQUIRED"
CAR_YEAR_REQUIRED = "CAR_YEAR_REQUIRED"
CAR_STATUS_REQUIRED = "CAR_YEAR_REQUIRED"

# Car Validations Messages
CAR_NOT_FOUND = "CAR_NOT_FOUND"  # CAR not found
CAR_SUCCESSFULLY_UPDATED = "CAR_SUCCESSFULLY_UPDATED"
CAR_SUCCESSFULLY_DELETED = "CAR_SUCCESSFULLY_DELETED"
CAR_SUCCESSFULLY_CREATED = "CAR_SUCCESSFULLY_CREATED"
CAR_ALREADY_EXIST = "CAR_ALREADY_EXIST"
CAR_PHOTO_REQUIRED = "CAR_PHOTO_REQUIRED"
CAR_MODEL_REQUIRED = "CAR_MODEL_REQUIRED"
CAR_TYPE_REQUIRED = "CAR_TYPE_REQUIRED"
CAR_PLATE_REQUIRED = "CAR_PLATE_REQUIRED"
CAR_BRAND_REQUIRED = "CAR_BRAND_REQUIRED"
CAR_YEAR_REQUIRED = "CAR_YEAR_REQUIRED"
CAR_STATUS_REQUIRED = "CAR_YEAR_REQUIRED"